[package]
name = "shrink-conflicts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
bpaf = { version = "0.7.7", features = ["derive", "color"] }
memchr = "2.5.0"
